# permissions for end users to view gateservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gateserver-viewer-role
rules:
- apiGroups:
  - ocgate.rh-fieldwork.com
  resources:
  - gateservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ocgate.rh-fieldwork.com
  resources:
  - gateservers/status
  verbs:
  - get
